
[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  framework = "#custom"
  port = 5173
  targetPort = 8080

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuração de notificações
[build.success]
  webhook = "${DEPLOY_WEBHOOK_URL}"

[build.environment]
  NODE_VERSION = "18"

