// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oenoqywcsztuljmdvaop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lbm9xeXdjc3p0dWxqbWR2YW9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUxODA1OTEsImV4cCI6MjA1MDc1NjU5MX0.7VsEwiD7o3AS9JSukOFZ0mAaKKPjKyIBCwAV1XS_ORA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);